CREATE TABLE users (
id BIGINT NOT NULL AUTO_INCREMENT,
username VARCHAR(45) NOT NULL,
first_name VARCHAR(45) NOT NULL,
last_name VARCHAR(45) NOT NULL,
phone_number VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
role VARCHAR(45) NOT NULL DEFAULT 'USER',
PRIMARY KEY (id),
UNIQUE INDEX username_UNIQUE (username ASC) VISIBLE,
UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
UNIQUE INDEX phone_number_UNIQUE (phone_number ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;