CREATE TABLE events (
id BIGINT NOT NULL,
event_action VARCHAR(45) NOT NULL,
date TIMESTAMP NOT NULL,
user_id BIGINT NOT NULL,
PRIMARY KEY (id),
INDEX user_fk_event_idx (user_id ASC) VISIBLE,
CONSTRAINT user_fk_event
FOREIGN KEY (user_id)
REFERENCES users (id)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
