CREATE TABLE user_file (
user_id BIGINT NOT NULL,
file_id BIGINT NOT NULL,
PRIMARY KEY (user_id, file_id),
INDEX file_idx (file_id ASC) VISIBLE,
CONSTRAINT user
FOREIGN KEY (user_id)
REFERENCES users (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT file
FOREIGN KEY (file_id)
REFERENCES files (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION);